#!/usr/bin/env bash
set -o errexit

echo "Installing system dependencies for GeoDjango..."
apt-get update
apt-get install -y \
    binutils \
    libproj-dev \
    gdal-bin \
    libgdal-dev \
    python3-gdal \
    libgeos-dev 

# Find GDAL libraries and determine their exact path
echo "Detecting GDAL libraries..."
GDAL_PATH=$(find /usr -name "libgdal.so*" | head -1)
GEOS_PATH=$(find /usr -name "libgeos_c.so*" | head -1)

echo "GDAL found at: $GDAL_PATH"
echo "GEOS found at: $GEOS_PATH"

# Create environment file for persistent settings
echo "Creating environment file..."
cat > /opt/render/project/.env << EOF
GDAL_LIBRARY_PATH=$GDAL_PATH
GEOS_LIBRARY_PATH=$GEOS_PATH
GDAL_DATA=/usr/share/gdal
PROJ_LIB=/usr/share/proj
EOF

# Also create a file Django can import
mkdir -p /opt/render/project/src/server/settings
cat > /opt/render/project/src/server/settings/gdal_paths.py << EOF
# Auto-generated by build script
GDAL_LIBRARY_PATH = '$GDAL_PATH'
GEOS_LIBRARY_PATH = '$GEOS_PATH'
EOF

echo "Installing Python dependencies..."
pip install -r requirements.txt

echo "Verifying settings..."
ls -la /opt/render/project/.env
ls -la /opt/render/project/src/server/settings/gdal_paths.py