services:
  - type: web
    name: nestquest
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn server.wsgi:application --bind=0.0.0.0:$PORT --workers=4
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        fromDatabase:
          name: nestquest-db
          property: connectionString
