services:
  - type: web
    name: nestquest
    env: python
    buildCommand: |
      ./build.sh
      python manage.py makemigrations  # Generate migration files
      python manage.py migrate
    startCommand: gunicorn server.wsgi:application --bind=0.0.0.0:$PORT --workers=4
    envVars:
      - key: RENDER
        value: "true"
      - key: DJANGO_SETTINGS_MODULE
        value: server.settings
      - key: GDAL_LIBRARY_PATH
        value: "/usr/lib/libgdal.so" # Replace with the actual path from logs
      - key: GEOS_LIBRARY_PATH
        value: "/usr/lib/libgeos_c.so" # Replace with the actual path from logs
      - key: GDAL_DATA
        value: "/usr/share/gdal"
      - key: PROJ_LIB
        value: "/usr/share/proj"
