/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgetpas` | `/forgetpas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bookmark` | `/bookmark`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/maps` | `/maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/pages/chatbox`; params?: Router.UnknownInputParams; } | { pathname: `/pages/makePost`; params?: Router.UnknownInputParams; } | { pathname: `/pages/mapviewing`; params?: Router.UnknownInputParams; } | { pathname: `/pages/notificationLayout`; params?: Router.UnknownInputParams; } | { pathname: `/pages/roomprofile`; params?: Router.UnknownInputParams; } | { pathname: `/pages/setting`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/forgetpas` | `/forgetpas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bookmark` | `/bookmark`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/maps` | `/maps`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/chatbox`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/makePost`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/mapviewing`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/notificationLayout`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/roomprofile`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/setting`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/forgetpas${`?${string}` | `#${string}` | ''}` | `/forgetpas${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bookmark${`?${string}` | `#${string}` | ''}` | `/bookmark${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/maps${`?${string}` | `#${string}` | ''}` | `/maps${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/pages/chatbox${`?${string}` | `#${string}` | ''}` | `/pages/makePost${`?${string}` | `#${string}` | ''}` | `/pages/mapviewing${`?${string}` | `#${string}` | ''}` | `/pages/notificationLayout${`?${string}` | `#${string}` | ''}` | `/pages/roomprofile${`?${string}` | `#${string}` | ''}` | `/pages/setting${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgetpas` | `/forgetpas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bookmark` | `/bookmark`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/maps` | `/maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/pages/chatbox`; params?: Router.UnknownInputParams; } | { pathname: `/pages/makePost`; params?: Router.UnknownInputParams; } | { pathname: `/pages/mapviewing`; params?: Router.UnknownInputParams; } | { pathname: `/pages/notificationLayout`; params?: Router.UnknownInputParams; } | { pathname: `/pages/roomprofile`; params?: Router.UnknownInputParams; } | { pathname: `/pages/setting`; params?: Router.UnknownInputParams; };
    }
  }
}
